### ISSUE TITLE
[ENHANCEMENT] Only allow Pandas.Series as user-provided input to stress models

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#455]
# Proposed enhancement

After discussions in the last year, we agreed to change the only allowed time series input of the Stress models and for the oseries to be pandas.Series with a pandas.DatetimeIndex. This means the pastas.TimeSeries object will not be allowed as input anymore and will only be used internally. The settings can exclusively be provided through the Stress models objects (see also #408), creating one place to set this. The purpose of these changes is to make it easier for users to understand what is happening and make the modelling process more transparent. The complexity of the code will also substantially decrease, making it easier to maintain the code in the future.

## To-do-list

- [x] Change all docstrings to document that only pandas.Series with pandas.DatetimeIndex is allowed.
- [x] Create a function called internally but also available to users to validate the time series.
- [x] Update the TimeSeries object to include all the changes and remove old functionality (see list below).
- [x] Raise errors when users use old TimeSeries functionalities for Pastas 0.23 (`check_input `function).
- [x] Update the load functions for pas-files to deal with the new TimeSeries format.
- [x] Update the load function to somehow deal with the old TimeSeries format (works, but it is a hack).
- [x] Add `get_settings` method to stressmodels, also through ml.get_stressmodel_settings.
- [x] Document the use of these and existing/new pre-processing functions in an example notebook 

## List of changes made to TimeSeries object:

- `freq_original` keyword is removed, because equidistant time series are now required. The `freq_original` attribute is maintained, but directly inferred using `pd.infer_freq`.
- `validated_series` attribute is removed, as method will error when input time series do not pass all checks and thus there is no need for this attribute anymore.
- method `multiply` is deprecated, as users should not access the whole TimeSeries object anymore. Instead, multiplication can be done as a pre-processing step.
- internal method `_normalize` is removed. as this can (and probably already is) done when pre-processing the time series. In this case the user is in control of how the time series are normalized (e.g., on what period). The process was not transparent in the old implementation. 
- The following settings arguments are removed:
  - `"fill_nan"` is removed from settings, as nan-values are not allowed anymore and all stress time series are equidistant.
  - `norm` is removed from settings, as _normalize is also removed.

## Expected behavior

ts = pd.read_csv("prec.csv", parse_dates=True).squeeze()
sm = ps.StressModel(ts, name="press", settings=settings_dict)

**List of related Issues:**

- #397
- #408 
- #68

## Disclaimer

This change is really complicated and bound to break things. It is extremely difficult to make these changes backward compatible, mostly to due the change of only allowing equidistant time series for stresses. The most safe option is to rerun the python script to recreate the pas-files. With the current implementation, it is however possible to load old pas-files. For existing scripts, Pastas will clearly indicate where it goes wrong and the fixes are generally very easy so adapting existing scripts should be very smooth.

**For all existing scripts where there the input data for the stresses was equidistant (e.g., All models with a RechargeModel) and checked by the modeller, the proposed changes will probably not at all affect the script or the results.** As a clear indication of this: most of the example scripts and notebooks need no or only few changes.

**Comment by raoulcollenteur** [comment]
List of changes made (for self-reference) to TimeSeries object:

- freq_original attribute and keyword is removed, because equidistant time series are now required.
- validated_series is removed, as method will error when input time series do not pass all checks.
- method multiply is deprecated, as users should not access the whole TimeSeries object anyway.
- keyword "fill_nan" is removed from settings, as nan-values are not allowed anymore.
- ...

**Comment by raoulcollenteur** [comment]
Also related to Issue #408, how to set the settings for stresses. I discuss this here to keep everything at one place. 

# For new stresmodels

**Option 1 for new stress models:**

`sm = ps.Stressmodel(stress, settings="prec")`

**Option 2 for new stress models:**

```
settings = {
  "fill_before": 0.0,
  "fill_after": 0.0,
  # Etcetera
}
sm = ps.Stressmodel(stress, settings=settings)
```

# Changing existing settings

This is more complicated, except for `tmin`,`tmax`, and `freq`, which can be set through `sm.update_stress` for all stresses at the same time.
