### ISSUE TITLE
[DEVELOPMENT] Add EmceeSolve for MCMC

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#559]
**Describe the proposed feature**

I propose to implement MCMC solver using 'emcee', instead of spotpy as tried in another attempt (#447). This package is much better developed and documented. The solver should allow for different likelihood functions/objective functions to be provided by the user.

**Expected usage**

`solver = ps.EmceeSolve(obj_func=ps.obj_funcs.method_name)`

**Additional context**

It would be nice to add a "distribution" column to ml.parameter, where the user can define the prior distributions (e.g., Normal, Uniform).

**To-do-list**

- [x] Add "dist" to ml.parameter to store the prior distribution
- [x] Find a way to allow user-provided likelihood functions
- [x] Find a way to have a solver which adds parameters 
- [x] Add set_parameter to solver
- [x] Update emcee example

**Comment by raoulcollenteur** [comment]
Added as per merge #572, closing Issue.
